/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.hdsb.gwss.ics3u.PerformanceTask;

/**
 *
 * @author maruiling
 */
import java.io.*;
import nu.xom.*;
import java.util.*;

public class Quiz extends javax.swing.JFrame {


    List<Element> questions = new ArrayList<Element>();
    int correctA = 0;
    int count = 1;
    int score = 0;
    int questionNumber;

    /**
     * Creates new form Prototype
     */
    public Quiz() {

        initComponents();
        QuestionPanel.setVisible(false);
        FinalPanel.setVisible(false);
        ResultPanel.setVisible(false);
        UserChoice.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Choices = new javax.swing.ButtonGroup();
        IntroPanel = new javax.swing.JPanel();
        WelcomeLabel = new javax.swing.JLabel();
        IntroductionScroll = new javax.swing.JScrollPane();
        IntroductionTextField = new javax.swing.JTextArea();
        StartButton = new javax.swing.JButton();
        QuestionPanel = new javax.swing.JPanel();
        QLabel = new javax.swing.JLabel();
        QStemScroll = new javax.swing.JScrollPane();
        Q1StemTextArea = new javax.swing.JTextArea();
        A = new javax.swing.JRadioButton();
        B = new javax.swing.JRadioButton();
        C = new javax.swing.JRadioButton();
        D = new javax.swing.JRadioButton();
        Submit = new javax.swing.JButton();
        ContentA = new javax.swing.JTextField();
        ContentB = new javax.swing.JTextField();
        ContentC = new javax.swing.JTextField();
        ContentD = new javax.swing.JTextField();
        QuestionScore = new javax.swing.JTextField();
        FinalPanel = new javax.swing.JPanel();
        ScoreLabel = new javax.swing.JLabel();
        Score = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        Message = new javax.swing.JTextArea();
        Exit = new javax.swing.JButton();
        ResultPanel = new javax.swing.JPanel();
        AnswerResultTextField = new javax.swing.JTextField();
        ResultScoreLabel = new javax.swing.JLabel();
        CorrectATextField = new javax.swing.JTextField();
        ScoreTextField = new javax.swing.JTextField();
        Next = new javax.swing.JButton();
        UserChoice = new javax.swing.JPanel();
        ChoiceTitle = new javax.swing.JLabel();
        SubjectTitle = new javax.swing.JLabel();
        Subject = new javax.swing.JComboBox<>();
        QuestionChoice = new javax.swing.JLabel();
        Questions = new javax.swing.JComboBox<>();
        iAmReady = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        IntroPanel.setBackground(new java.awt.Color(255, 255, 255));

        WelcomeLabel.setBackground(new java.awt.Color(255, 255, 255));
        WelcomeLabel.setFont(new java.awt.Font("Stencil Std", 0, 24)); // NOI18N
        WelcomeLabel.setText("WELCOME TO the QUIZ");

        IntroductionTextField.setEditable(false);
        IntroductionTextField.setColumns(20);
        IntroductionTextField.setRows(5);
        IntroductionTextField.setText("This quiz can be used to test the subject you choose.\n\nThis quiz contains max 10 questions.\n\nPressure SATART to begin the quiz.\n\nGOOD LUCK! :)");
        IntroductionTextField.setToolTipText("");
        IntroductionTextField.setBorder(null);
        IntroductionScroll.setViewportView(IntroductionTextField);

        StartButton.setText("START");
        StartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout IntroPanelLayout = new javax.swing.GroupLayout(IntroPanel);
        IntroPanel.setLayout(IntroPanelLayout);
        IntroPanelLayout.setHorizontalGroup(
            IntroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IntroPanelLayout.createSequentialGroup()
                .addGroup(IntroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IntroPanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(IntroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IntroductionScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(IntroPanelLayout.createSequentialGroup()
                                .addGap(134, 134, 134)
                                .addComponent(WelcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(IntroPanelLayout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(StartButton)))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        IntroPanelLayout.setVerticalGroup(
            IntroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IntroPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(WelcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(IntroductionScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(StartButton)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        QuestionPanel.setBackground(new java.awt.Color(255, 255, 255));

        QLabel.setFont(new java.awt.Font("STHeiti", 0, 36)); // NOI18N
        QLabel.setText("Question 1");

        Q1StemTextArea.setEditable(false);
        Q1StemTextArea.setColumns(20);
        Q1StemTextArea.setRows(5);
        QStemScroll.setViewportView(Q1StemTextArea);

        Choices.add(A);
        A.setText("A");

        Choices.add(B);
        B.setText("B");

        Choices.add(C);
        C.setText("C");

        Choices.add(D);
        D.setText("D");

        Submit.setText("SUBMIT");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        ContentA.setEditable(false);

        ContentB.setEditable(false);

        ContentC.setEditable(false);

        ContentD.setEditable(false);

        QuestionScore.setEditable(false);

        javax.swing.GroupLayout QuestionPanelLayout = new javax.swing.GroupLayout(QuestionPanel);
        QuestionPanel.setLayout(QuestionPanelLayout);
        QuestionPanelLayout.setHorizontalGroup(
            QuestionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuestionPanelLayout.createSequentialGroup()
                .addGroup(QuestionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(QuestionPanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(QuestionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(QuestionPanelLayout.createSequentialGroup()
                                .addComponent(C)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ContentC, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(QuestionPanelLayout.createSequentialGroup()
                                .addComponent(B)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ContentB, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(QuestionPanelLayout.createSequentialGroup()
                                .addComponent(D)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ContentD, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(QuestionPanelLayout.createSequentialGroup()
                                .addComponent(A)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ContentA, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(QuestionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, QuestionPanelLayout.createSequentialGroup()
                                    .addComponent(QLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(QuestionScore, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(QStemScroll, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(QuestionPanelLayout.createSequentialGroup()
                        .addGap(316, 316, 316)
                        .addComponent(Submit)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        QuestionPanelLayout.setVerticalGroup(
            QuestionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuestionPanelLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(QuestionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(QLabel)
                    .addComponent(QuestionScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(QStemScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(QuestionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(A)
                    .addComponent(ContentA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(QuestionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B)
                    .addComponent(ContentB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(QuestionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(C)
                    .addComponent(ContentC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(QuestionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(D)
                    .addComponent(ContentD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Submit)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        FinalPanel.setBackground(new java.awt.Color(255, 255, 255));

        ScoreLabel.setBackground(new java.awt.Color(255, 255, 255));
        ScoreLabel.setFont(new java.awt.Font("DIN Alternate", 0, 36)); // NOI18N
        ScoreLabel.setText("Your Score Is: ");

        Score.setEditable(false);
        Score.setFont(new java.awt.Font("DIN Alternate", 0, 36)); // NOI18N

        Message.setColumns(20);
        Message.setRows(5);
        jScrollPane7.setViewportView(Message);

        Exit.setText("EXIT");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FinalPanelLayout = new javax.swing.GroupLayout(FinalPanel);
        FinalPanel.setLayout(FinalPanelLayout);
        FinalPanelLayout.setHorizontalGroup(
            FinalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FinalPanelLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(FinalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FinalPanelLayout.createSequentialGroup()
                        .addComponent(ScoreLabel)
                        .addGap(18, 18, 18)
                        .addComponent(Score, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(176, 176, 176))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FinalPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FinalPanelLayout.createSequentialGroup()
                        .addComponent(Exit)
                        .addGap(325, 325, 325))))
        );
        FinalPanelLayout.setVerticalGroup(
            FinalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FinalPanelLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(FinalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ScoreLabel)
                    .addComponent(Score, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(Exit)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        ResultPanel.setBackground(new java.awt.Color(255, 255, 255));

        AnswerResultTextField.setEditable(false);
        AnswerResultTextField.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N

        ResultScoreLabel.setFont(new java.awt.Font("Lucida Sans Typewriter", 2, 24)); // NOI18N
        ResultScoreLabel.setText("Your Score By Now Is: ");

        CorrectATextField.setEditable(false);
        CorrectATextField.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        CorrectATextField.setText("The correct answer is: ");

        ScoreTextField.setEditable(false);
        ScoreTextField.setFont(new java.awt.Font("Lucida Sans Typewriter", 2, 24)); // NOI18N

        Next.setText("NEXT");
        Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ResultPanelLayout = new javax.swing.GroupLayout(ResultPanel);
        ResultPanel.setLayout(ResultPanelLayout);
        ResultPanelLayout.setHorizontalGroup(
            ResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResultPanelLayout.createSequentialGroup()
                .addContainerGap(155, Short.MAX_VALUE)
                .addGroup(ResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ResultPanelLayout.createSequentialGroup()
                        .addComponent(AnswerResultTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(221, 221, 221))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ResultPanelLayout.createSequentialGroup()
                        .addComponent(CorrectATextField, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(177, 177, 177))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ResultPanelLayout.createSequentialGroup()
                        .addComponent(ResultScoreLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ScoreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ResultPanelLayout.createSequentialGroup()
                        .addComponent(Next)
                        .addGap(322, 322, 322))))
        );
        ResultPanelLayout.setVerticalGroup(
            ResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResultPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(AnswerResultTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(CorrectATextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(ResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ResultScoreLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ScoreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(Next)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        UserChoice.setBackground(new java.awt.Color(255, 255, 255));
        UserChoice.setPreferredSize(new java.awt.Dimension(742, 417));

        ChoiceTitle.setText("Please choose the subject and the number of questions");

        SubjectTitle.setText("Subject: ");

        Subject.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Computer Science", "Chemistry", "Physics", "Biology" }));

        QuestionChoice.setText("Number of Questions: ");

        Questions.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        iAmReady.setText("I AM READY");
        iAmReady.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iAmReadyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UserChoiceLayout = new javax.swing.GroupLayout(UserChoice);
        UserChoice.setLayout(UserChoiceLayout);
        UserChoiceLayout.setHorizontalGroup(
            UserChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UserChoiceLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(UserChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UserChoiceLayout.createSequentialGroup()
                        .addComponent(SubjectTitle)
                        .addGap(18, 18, 18)
                        .addComponent(Subject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(UserChoiceLayout.createSequentialGroup()
                        .addComponent(QuestionChoice)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Questions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(245, 245, 245))
            .addGroup(UserChoiceLayout.createSequentialGroup()
                .addGroup(UserChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UserChoiceLayout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(ChoiceTitle))
                    .addGroup(UserChoiceLayout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(iAmReady)))
                .addContainerGap(197, Short.MAX_VALUE))
        );
        UserChoiceLayout.setVerticalGroup(
            UserChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserChoiceLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(ChoiceTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101)
                .addGroup(UserChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SubjectTitle)
                    .addComponent(Subject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(UserChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QuestionChoice)
                    .addComponent(Questions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(iAmReady)
                .addGap(55, 55, 55))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(IntroPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(QuestionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(FinalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(ResultPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(UserChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(IntroPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(QuestionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(FinalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(ResultPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(UserChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartButtonActionPerformed
        // TODO add your handling code here:
        
        IntroPanel.setVisible(false);
        UserChoice.setVisible(true);

    }//GEN-LAST:event_StartButtonActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        // TODO add your handling code here:
        int selection = -1;

        if (A.isSelected()) {
            selection = 1;
        } else if (B.isSelected()) {
            selection = 2;
        } else if (C.isSelected()) {
            selection = 3;
        } else if (D.isSelected()) {
            selection = 4;
        }

        if (selection == correctA) {
            AnswerResultTextField.setText("CORRECT!");
            score++;
        } else {
            AnswerResultTextField.setText("SORRY :(");
        }

        QuestionPanel.setVisible(false);
        ResultPanel.setVisible(true);

        char anwser = (char) (correctA + 64);
        CorrectATextField.setText("The correct answer is " + anwser);
        ScoreTextField.setText(score + "/" + questionNumber);
        count++;
    }//GEN-LAST:event_SubmitActionPerformed

    private void NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextActionPerformed
        // TODO add your handling code here:
        if (count <= questionNumber) {
            Choices.clearSelection();
            ResultPanel.setVisible(false);
            QuestionPanel.setVisible(true);
            QLabel.setText("Question " + count);
            int random = (int) (Math.random() * questions.size());
            Element Q = questions.remove(random);
            Q1StemTextArea.setText(Q.getChildElements().get(0).getValue());
            ContentA.setText(Q.getChildElements().get(1).getValue());
            ContentB.setText(Q.getChildElements().get(2).getValue());
            ContentC.setText(Q.getChildElements().get(3).getValue());
            ContentD.setText(Q.getChildElements().get(4).getValue());
            correctA = Integer.parseInt(Q.getChildElements().get(5).getValue());
            QuestionScore.setText(score + "/" + questionNumber);
        } else {
            ResultPanel.setVisible(false);
            FinalPanel.setVisible(true);
            Score.setText(score + "/" + questionNumber);
            if (score * 1.0 / questionNumber <= 0.20) {
                Message.setText("You need study about this subject first.");
            } else if (score * 1.0 / questionNumber <= 0.40) {
                Message.setText("You need to improve the basic knowledge of this subject.");
            } else if (score * 1.0 / questionNumber <= 0.60) {
                Message.setText("You have little knowledge about this subject and you need to work harder.");
            } else if (score * 1.0 / questionNumber <= 0.80) {
                Message.setText("You have the basic knowledge about this subject but you need to study further.");
            } else if (score * 1.0 / questionNumber < 1.0) {
                Message.setText("You have deep knowledge about this subject and you need to filling in the gaps.");
            } else if (score == questionNumber) {
                Message.setText("You have done an great job! ");
            }
        }

    }//GEN-LAST:event_NextActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void iAmReadyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iAmReadyActionPerformed
        // TODO add your handling code here:
        File f = new File("");
        if (String.valueOf(Subject.getSelectedItem()).compareTo("Computer Science") == 0) {
            f = new File("CSQuestions.xml");
        } else if (String.valueOf(Subject.getSelectedItem()).compareTo("Chemistry") == 0) {
            f = new File("ChemistryQuestion.xml");
        } else if (String.valueOf(Subject.getSelectedItem()).compareTo("Biology") == 0) {
            f = new File("BiologyQuestion.xml");
        } else if (String.valueOf(Subject.getSelectedItem()).compareTo("Physics") == 0) {
            f = new File("PhysicsQuestion.xml");
        }

        Builder builder = new Builder();
        try {
            Document doc = builder.build(f);
            Element root = doc.getRootElement();
            Elements question = root.getChildElements();
            for (int i = 0; i < question.size(); i++) {
                questions.add(question.get(i));
            }
            questionNumber = Integer.parseInt(String.valueOf(Questions.getSelectedItem()));
            
        } catch (Exception e) {
            System.err.println(e);
        }
      
        UserChoice.setVisible(false);
        QuestionPanel.setVisible(true);
        QLabel.setText("Question " + count);
        int random = (int) (Math.random() * 10);
        Element Q = questions.remove(random);
        Q1StemTextArea.setText(Q.getChildElements().get(0).getValue());
        ContentA.setText(Q.getChildElements().get(1).getValue());
        ContentB.setText(Q.getChildElements().get(2).getValue());
        ContentC.setText(Q.getChildElements().get(3).getValue());
        ContentD.setText(Q.getChildElements().get(4).getValue());
        correctA = Integer.parseInt(Q.getChildElements().get(5).getValue());
        QuestionScore.setText(score + "/" + questionNumber);
    }//GEN-LAST:event_iAmReadyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                    new Quiz().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton A;
    private javax.swing.JTextField AnswerResultTextField;
    private javax.swing.JRadioButton B;
    private javax.swing.JRadioButton C;
    private javax.swing.JLabel ChoiceTitle;
    private javax.swing.ButtonGroup Choices;
    private javax.swing.JTextField ContentA;
    private javax.swing.JTextField ContentB;
    private javax.swing.JTextField ContentC;
    private javax.swing.JTextField ContentD;
    private javax.swing.JTextField CorrectATextField;
    private javax.swing.JRadioButton D;
    private javax.swing.JButton Exit;
    private javax.swing.JPanel FinalPanel;
    private javax.swing.JPanel IntroPanel;
    private javax.swing.JScrollPane IntroductionScroll;
    private javax.swing.JTextArea IntroductionTextField;
    private javax.swing.JTextArea Message;
    private javax.swing.JButton Next;
    private javax.swing.JTextArea Q1StemTextArea;
    private javax.swing.JLabel QLabel;
    private javax.swing.JScrollPane QStemScroll;
    private javax.swing.JLabel QuestionChoice;
    private javax.swing.JPanel QuestionPanel;
    private javax.swing.JTextField QuestionScore;
    private javax.swing.JComboBox<String> Questions;
    private javax.swing.JPanel ResultPanel;
    private javax.swing.JLabel ResultScoreLabel;
    private javax.swing.JTextField Score;
    private javax.swing.JLabel ScoreLabel;
    private javax.swing.JTextField ScoreTextField;
    private javax.swing.JButton StartButton;
    private javax.swing.JComboBox<String> Subject;
    private javax.swing.JLabel SubjectTitle;
    private javax.swing.JButton Submit;
    private javax.swing.JPanel UserChoice;
    private javax.swing.JLabel WelcomeLabel;
    private javax.swing.JButton iAmReady;
    private javax.swing.JScrollPane jScrollPane7;
    // End of variables declaration//GEN-END:variables
}
